### ISSUE TITLE
Find node configuration

### ISSUE THREAD

**Issue by sebicm** [digitalpetri/opc-ua-demo-server#4]
I am using this demo server to provide me with some sample data for linking an opc server with a an influxdb.
However I could not find any documentation on the node configuration for the demo server? How can I find the nodes that provide me with sample data?

**Comment by kevinherron** [comment]
These fragments each contribute some part of the overall demo address space: https://github.com/digitalpetri/opc-ua-demo-server/tree/master/src/main/kotlin/com/digitalpetri/opcua/server/namespaces/demo
