### ISSUE TITLE
Did the public server down?

### ISSUE THREAD

**Issue by dcsuibian** [digitalpetri/opc-ua-demo-server#5]
Can not connect to `opc.tcp://milo.digitalpetri.com:62541/milo`.

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/54771493/157799385-9f20aa71-d019-42aa-8c9e-e4385f4e826b.png">

Ping is also failed.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/54771493/157799441-95cb12a4-47e8-486b-b468-e0345ba66066.png">

**Comment by kevinherron** [comment]
Hmm, thanks, I'll look into it.

**Comment by kevinherron** [comment]
Ok, not sure what happened, but it's back online. I had to power cycle the Digital Ocean droplet before I could even SSH into it.

**Comment by kevinherron** [comment]
@ashhassan100 I think the problem must be on your side, I am able to connect:
<img width="1112" alt="Screen Shot 2022-06-29 at 12 28 28 PM" src="https://user-images.githubusercontent.com/340273/176520004-11f5a74c-d910-446d-b36c-69e23aed3958.png">

**Comment by ashhassan100** [comment]
<img width="1005" alt="Screen Shot 2022-06-29 at 12 34 29 PM" src="https://user-images.githubusercontent.com/59520753/176521086-3d4d3f42-b7fb-450b-a84c-e53d289df161.png">
I'm not sure why mine doesn't connect. Do you have any suggestion or ideas?

**Comment by kevinherron** [comment]
Maybe you can get a Wireshark capture and see? Check your firewall? Is this a work or home network?

**Comment by sebastianvoss** [comment]
Thanks for providing the demo server! It currently seems to be down:

```
telnet milo.digitalpetri.com 62541
Trying 134.209.49.44...
telnet: connect to address 134.209.49.44: Connection refused
telnet: Unable to connect to remote host
```

**Comment by kevinherron** [comment]
@sebastianvoss thanks for the heads up - it's back online.

Every few weeks the Docker container just dies even though CPU and memory are not under pressure... 😖

**Comment by sebastianvoss** [comment]
The server might need another restart.

**Comment by kevinherron** [comment]
> The server might need another restart.

Ok, done. Things are getting worse... I'll try to look into it this week but it's a really busy in-office week at work.
