### ISSUE TITLE
Potential wrong behavior with responses to FindServer / GetEndpoints

### ISSUE THREAD

**Issue by sruehl** [digitalpetri/opc-ua-demo-server#9]
Reading the spec at https://reference.opcfoundation.org/Core/Part4/v104/docs/5.4.2 it seems like one can utilize `FindServer`/`GetEndpoints` to find more about a endpoint by calling the `FindServers` with the endoint `some-hostname:4840`.
Doing that with the public endpoint returns to me a `StatusBadTCPEndpointURLInvalid`.
It only works when you attach a `/milo` to the endpoint and using the port `62541`.
On contrast if you use this server here [opclabs public demo server](https://opclabs.doc-that.com/files/onlinedocs/QuickOpc/Latest/User's%20Guide%20and%20Reference-QuickOPC/OPC%20UA%20Sample%20Server.html) it works on the endpoint it defines there `opc.tcp://opcua.demo-this.com:51210/UA/SampleServer` as well as the port 4840 (also both with ommiting the path). The responses of FindServers include on the non standard port only information about the one server and on the standard port 4840 all servers.
From my humble opinion this is the way it would make sense e.g. how I am supposed to get information about a host if I have to guess port and url path to get information about a server.
So I'm no expert by any means and I can't figure out from the OPC-UA spec how this all is supposed to work but for me it would make sense to always provide `4840` as this is the whole purpose of making it able to be discovered.
Also to quote https://reference.opcfoundation.org/Core/Part4/v104/docs/5.4.2 "Every [Server](https://reference.opcfoundation.org/search/17?t=Server) shall provide a [DiscoveryEndpoint](https://reference.opcfoundation.org/search/17?t=DiscoveryEndpoint) that supports this [Service](https://reference.opcfoundation.org/search/17?t=Service)."

**Comment by sruehl** [comment]
Edit: Ignore the quote at the end, as far as I know the server does provide a discovery endpoint `../milo/discovery` you just need to find it 😄

**Comment by sruehl** [comment]
What might be more relevant is this section "A [Server](https://reference.opcfoundation.org/search/17?t=Server) may have multiple [HostNames](https://reference.opcfoundation.org/search/17?t=HostNames). For this reason, the [Client](https://reference.opcfoundation.org/search/17?t=Client) shall pass the URL it used to connect to the [Endpoint](https://reference.opcfoundation.org/search/17?t=Endpoint) to this [Service](https://reference.opcfoundation.org/search/17?t=Service). The implementation of this [Service](https://reference.opcfoundation.org/search/17?t=Service) shall use this information to return responses that are accessible to the [Client](https://reference.opcfoundation.org/search/17?t=Client) via the provided URL."

So from my understanding the endpoint is only passed to extract the hostname in those cases

**Comment by sruehl** [comment]
regarding the `StatusBadTCPEndpointURLInvalid`: I suspect the root cause/problem might be that the Milo-Demo-Server rejects the `HEL` message when it doesn't have the complete endpoint url it expects. Therefore it never reaches the point to be able to call the FindServers

**Comment by sruehl** [comment]
reading the spec on the hello https://reference.opcfoundation.org/Core/Part6/v104/docs/7.1.2.3:
"or if it does not recognize the resource identified by the URL.". It leaves some room for interpretation but in my case it should recognize the resource as it is part of the known endpoints

**Comment by kevinherron** [comment]
This is working as intended. The server only responds to explicitly configured endpoint URLs. The idea being, that at different endpoint URLs you can have different services or behaviors mounted.

**Comment by kevinherron** [comment]
You are free to also bind and configure just discovery services on `host:4840` in addition. You would need to make sure these point to the session endpoints at `host:$port/$path` as expected.
